defaults: &defaults
  host: localhost
  # slaves:
  # - host: slave1.local
  # port: 27018
  # - host: slave2.local
  # port: 27019

development:
  <<: *defaults
  database: espresse_webpage_development

test:
  <<: *defaults
  database: espresse_webpage_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
